#include "sdk.h"
std::vector<std::string> weaponNames = {
	"Unarmed",
	"Brass knuckles",
	"Golf club",
	"Nightstick",
	"Knife",
	"Baseball bat",
	"Shovel",
	"Pool cue",
	"Katana",
	"Chainsaw",
	"Dildo",
	"Dildo",
	"Vibrator",
	"Vibrator",
	"Flowers",
	"Cane",
	"Grenade",
	"Tear gas",
	"Molotov",
	"Rocket",
	"Heat-seeking rocket",
	"Freefall bomb?",
	"Pistol",
	"Silenced pistol",
	"Desert eagle",
	"Shotgun",
	"Sawnoff shotgun",
	"Combat shotgun",
	"Micro Uzi",
	"MP5",
	"AK47",
	"M4",
	"Tec 9",
	"Rifle",
	"Sniper rifle",
	"Rocket launcher",
	"Heat-seeking rocket launcher",
	"Flamethrower",
	"Minigun",
	"Remote stachel charge",
	"Detonator",
	"Spray can",
	"Extinguisher",
	"Camera",
	"Night vision",
	"Thermal vision",
	"Parachute",

	"Last weapon type",
	"Armour",
	"Rammed by car",
	"Run over by car",
	"Explosion",
	"Uzi drive by",
	"Drowning",
	"Fall",
	"Unidentified",
	"Any melee",
	"Any weapon",
	"Flare",
	"Tank grenade",

	//if you go out of bounds
	"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""
};